### ISSUE TITLE
Various comments

### ISSUE THREAD

**Issue by JoshData** [OpenGovDC/Transparency--Open-Government-Open-Data-Directive#2]
Hello!

I wrote about a number of issues with the directive here: http://razor.occams.info/blog/2014/07/21/dcs-open-data-directive-adopts-the-mistakes-made-by-the-white-house/

To summarize:

There are many things to like about the Directive, including the mention of a potential new Chief Data Officer position, the use of open formats, and the goal of promoting reuse. The framing in terms of transparency, participation, and collaboration — lifted from Obama’s 2009 open government memo and adopted in the Mayor’s 2011 memorandum on transparency and open government – is good. (Though not great. The White House never managed to actually execute the collaboration part.)

But much of it is also undercut by a notion of conditional access to government information. There is confusion over whether the policy aims to achieve no restrictions or whether it seeks to institutionalize attribution, indemnification, and so on. For instance, “open license” does not mean “no restrictions.” “Open license” also presumes the work is copyrighted, but data per se is generally not subject to copyright protections. The directive also creates a practice where data users must agree to a contract first. It's not "open data" if the public has to agree to use it on the government's terms. Access to information about the government that comes with restrictions on use is an anathema to accountability and transparency and respect for the public.

I will be encouraging potential data users to FOIA for the same information rather than get it from the DC data catalog under the terms proposed in the Directive.

**Comment by DCOPENGOV** [comment]
Hi Josh! First thank you for taking the time to read through the policy and for providing the link. We are compiling a list of comments from the public which will be submitted to the Mayor via the Director of the Office of Open Government. We will also hold an open government/FOIA and government ethics event in October that will be free and open to the public, please check our website, www.bega-dc.gov as we will post date and location info in the next few weeks.

**Comment by JoshData** [comment]
Thank you for providing a place to comment on the directive!
